# Generated by Django 5.1.4 on 2025-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=50)),
                ('corro', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
