# Generated by Django 5.1.4 on 2025-01-12 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='corro',
            new_name='correo',
        ),
    ]
